name: newlight church
tagline: a home church in the fox valley
markdown: redcarpet
paginate: 4
paginate_path: "blog/page:num"
prose:
  rooturl: '_posts'
  siteurl: 'http://newlightchurch.github.io/'
  metadata:
    _posts:
    - name: "layout"
      field:
        element: "hidden"
          value: "blog"
    - name: "title"
      field:
        element: "text"
        type: "text"
	- name: "description"
	  field:
	    element: "text"
	    type: "text"